### ISSUE TITLE
[Linux] Firefox CSD Problems

### ISSUE THREAD

**Issue by veyselerden** [rstacruz/firefox-stealthfox#4]
Firstly, thank you for this beautiful css.

Well coming to one of the problems:

1- As you can see here buttons overlapping the close button on the right:
![2019-01-11 18-54-45 ekran goruntusu](https://user-images.githubusercontent.com/12845347/51044713-d3aa9c80-15d2-11e9-936a-9536169c3878.png)

2- This color shift in the csd area:
![2019-01-11 18-54-41 ekran goruntusu](https://user-images.githubusercontent.com/12845347/51044750-efae3e00-15d2-11e9-97aa-553e36b44d41.png)

Thank you again, this is really good customization for Firefox!

**Comment by rstacruz** [comment]
Thanks for the report! I've noticed this myself, but it only happens when you check "Title Bar" under customize firefox

**Comment by veyselerden** [comment]
Seems like you've fixed it. Thank you so much for your work!
